name: JSON Validation

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          base_dir: metadata